

services:
  # Base de Datos Principal
  postgres-db:
    image: postgres:15-alpine
    container_name: power_nutri_db
    restart: always
    environment:
      POSTGRES_USER: power_user
      POSTGRES_PASSWORD: power_password_2026
      POSTGRES_DB: power_nutri_app
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Caché para sesiones y rendimiento
  redis-cache:
    image: redis:7-alpine
    container_name: power_nutri_redis
    ports:
      - "6379:6379"

  power_nutri_backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: power_nutri_backend
    restart: always
    ports:
      - "3002:3002"
    environment:
      # Conectar al alias del db 'postgres-db:5432'
      - DATABASE_URL=postgresql://power_user:power_password_2026@postgres-db:5432/power_nutri_app?schema=public
      - JWT_SECRET=super_secret_power_nutri_2026
    depends_on:
      - postgres-db
    volumes:
      - backend_uploads:/app/uploads

volumes:
  postgres_data:
  backend_uploads: